# -*- coding: utf-8 -*-
"""RAG_PipeLine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14KbQTPu1GdqGTHT3Glwclxs3Fvx2fOk9

**Data Ingestion**
"""

from google.colab import drive
drive.mount('/content/drive')

## document data structure
from langchain_core.documents import Document

doc=Document(
    page_content="This is the main text content I am using to create RAG",
    metadata={
        "source":"example.txt",
        "pages":1,
        "author":"Saurabh Sarkar",
        "date_created":"2025:12:12"
    }
)
doc

## Create a Simple txt file
import os
os.makedirs("../data/text_files",exist_ok=True)

sample_texts={
    "../data/text_files/python_intro.txt":"""Python is a high-level, general-purpose programming language. Its design philosophy emphasizes code readability with the use of significant indentation.[34] Python is dynamically type-checked and garbage-collected. It supports multiple programming paradigms, including structured (particularly procedural), object-oriented and functional programming.

Guido van Rossum began working on Python in the late 1980s as a successor to the ABC programming language. Python 3.0, released in 2008, was a major revision and not completely backward-compatible with earlier versions. Beginning with Python 3.5,[35] capabilities and keywords for typing were added to the language, allowing optional static typing.[36] As of 2025, the Python Software Foundation supports Python 3.10, 3.11, 3.12, 3.13, and 3.14, following the projects annual release cycle and five-year support policy. Earlier versions in the 3.x series have reached end-of-life and no longer receive security updates.

Python has gained widespread use in the machine learning community.[37][38][39][40] It is widely taught as an introductory programming language.[41] Since 2003, Python has consistently ranked in the top ten of the most popular programming languages in the TIOBE Programming Community Index, which ranks based on searches in 24 platforms.[42]

History
Main article: History of Python

The designer of Python, Guido van Rossum, at PyCon US 2024
Python was conceived in the late 1980s[43] by Guido van Rossum at Centrum Wiskunde & Informatica (CWI) in the Netherlands.[44] It was designed as a successor to the ABC programming language, which was inspired by SETL,[45] capable of exception handling and interfacing with the Amoeba operating system.[13] Python implementation began in December 1989.[44] Van Rossum first released it in 1991 as Python 0.9.0.[44] Van Rossum assumed sole responsibility for the project, as the lead developer, until 12 July 2018, when he announced his "permanent vacation" from responsibilities as Python's "benevolent dictator for life" (BDFL); this title was bestowed on him by the Python community to reflect his long-term commitment as the project's chief decision-maker.[46] (He has since come out of retirement and is self-titled "BDFL-emeritus".) In January 2019, active Python core developers elected a five-member Steering Council to lead the project.[47][48]

The name Python derives from the British comedy series Monty Python's Flying Circus.[49] (See § Naming.)

Python 2.0 was released on 16 October 2000, featuring many new features such as list comprehensions, cycle-detecting garbage collection, reference counting, and Unicode support.[50] Python 2.7's end-of-life was initially set for 2015, and then postponed to 2020 out of concern that a large body of existing code could not easily be forward-ported to Python 3.[51][52] It no longer receives security patches or updates.[53][54] While Python 2.7 and older versions are officially unsupported, a different unofficial Python implementation, PyPy, continues to support Python 2, i.e., "2.7.18+" (plus 3.11), with the plus signifying (at least some) "backported security updates".[55]

Python 3.0 was released on 3 December 2008, and was a major revision and not completely backward-compatible with earlier versions, with some new semantics and changed syntax. Python 2.7.18, released in 2020, was the last release of Python 2.[56] Several releases in the Python 3.x series have added new syntax to the language, and made a few (considered very minor) backward-incompatible changes.

As of December 2025, Python 3.14.2 is the latest stable release. All older 3.x versions had a security update down to Python 3.9.24 then again with 3.9.25, the final version in 3.9 series. Python 3.10 is, since November 2025, the oldest supported branch.[57] Python 3.15 has an alpha released, and Android has an official downloadable executable available for Python 3.14. Releases receive two years of full support followed by three years of security support.

Design philosophy and features
Python is a multi-paradigm programming language. Object-oriented programming and structured programming are fully supported, and many of their features support functional programming and aspect-oriented programming – including metaprogramming[58] and metaobjects.[59] Many other paradigms are supported via extensions, including design by contract[60][61] and logic programming.[62] Python is often referred to as a 'glue language'[63] because it is purposely designed to be able to integrate components written in other languages.

Python uses dynamic typing and a combination of reference counting and a cycle-detecting garbage collector for memory management.[64] It uses dynamic name resolution (late binding), which binds method and variable names during program execution.

Python's design offers some support for functional programming in the "Lisp tradition". It has filter, map, and reduce functions; list comprehensions, dictionaries, sets, and generator expressions.[65] The standard library has two modules (itertools and functools) that implement functional tools borrowed from Haskell and Standard ML.[66]

Python's core philosophy is summarized in the Zen of Python (PEP 20) written by Tim Peters, which includes aphorisms such as these:[67]

Explicit is better than implicit.
Simple is better than complex.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
There should be one-- and preferably only one --obvious way to do it.
However, Python has received criticism for violating these principles and adding unnecessary language bloat.[68] Responses to these criticisms note that the Zen of Python is a guideline rather than a rule.[69] The addition of some new features had been controversial: Guido van Rossum resigned as Benevolent Dictator for Life after conflict about adding the assignment expression operator in Python 3.8.[70][71]

Nevertheless, rather than building all functionality into its core, Python was designed to be highly extensible via modules. This compact modularity has made it particularly popular as a means of adding programmable interfaces to existing applications. Van Rossum's vision of a small core language with a large standard library and easily extensible interpreter stemmed from his frustrations with ABC, which represented the opposite approach.[43]

Python claims to strive for a simpler, less-cluttered syntax and grammar, while giving developers a choice in their coding methodology. Python lacks do while loops, which Rossum considered harmful.[72] In contrast to Perl's motto "there is more than one way to do it", Python advocates an approach where "there should be one – and preferably only one – obvious way to do it".[67] In practice, however, Python provides many ways to achieve a given goal. There are at least three ways to format a string literal, with no certainty as to which one a programmer should use.[73] Alex Martelli is a Fellow at the Python Software Foundation and Python book author; he wrote that "To describe something as 'clever' is not considered a compliment in the Python culture."[74]

Python's developers typically prioritise readability over performance. For example, they reject patches to non-critical parts of the CPython reference implementation that would offer increases in speed that do not justify the cost of clarity and readability.[75][failed verification] Execution speed can be improved by moving speed-critical functions to extension modules written in languages such as C, or by using a just-in-time compiler like PyPy. Also, it is possible to transpile to other languages. However, this approach either fails to achieve the expected speed-up, since Python is a very dynamic language, or only a restricted subset of Python is compiled (with potential minor semantic changes).[76]"""
}

for filepath,content in sample_texts.items():
  with open(filepath,'w',encoding='utf-8') as f:
    f.write(content)
print("Sample text files created!")

### TextLoader
!pip install langchain-community
from langchain_community.document_loaders import TextLoader
loader=TextLoader("../data/text_files/python_intro.txt",encoding='utf-8')
document=loader.load()
print(document)

### Directory Loader
from langchain_community.document_loaders import DirectoryLoader
## load all the text files from the directory
dir_loader=DirectoryLoader(
    "../data/text_files",
    glob="**/*.txt", # pattern to match files
    loader_cls=TextLoader, ## loader class to use
    loader_kwargs={'encoding':'utf-8'}, ## kwargs to pass to the loader
    show_progress=False
)

documents=dir_loader.load()
documents

!pip install pymupdf
from langchain_community.document_loaders import PyMuPDFLoader

## load all the text files from the directory
dir_loader=DirectoryLoader(
    "/content/", # Changed path from "../data/pdf_files" to "/content/"
    glob="**/*.pdf", # pattern to match files
    loader_cls=PyMuPDFLoader, ## loader class to use
    show_progress=False
)

documents=dir_loader.load()
documents

type(documents[0])

"""**RAG Pipelines - Data Ingestion to Vector DB PipeLine**"""

import os
from langchain_community.document_loaders import PyPDFLoader,PyMuPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from pathlib import Path

## Read all the pdf's inside the directory

def process_all_pdfs(pdf_directory):
  """Process all pdf files in a directory"""
  all_documents=[]
  pdf_dir=Path(pdf_directory)

  # find all PDF Files recursively
  # Changed the directory to '/content/' to match the location of the uploaded PDF files.
  pdf_files=list(Path('/content/').glob("**/*.pdf"))

  print(f"Found {len(pdf_files)} PDF files to process")

  for pdf_file in pdf_files:
    print(f"\nProcessing {pdf_file.name}")
    try:
      loader=PyMuPDFLoader(str(pdf_file))
      documents=loader.load()
      ## add source information to metadata
      for doc in documents:
        doc.metadata['source_file']=pdf_file.name
        doc.metadata['file_type']='pdf'
      all_documents.extend(documents)
      print(f"Loaded {len(documents)} pages")
    except Exception as e:
      print(f"Error processing {pdf_file.name}: {e}")
  print(f"Total documents loaded: {len(all_documents)}")
  return all_documents


## process all PDFS in the data directory
# The argument to process_all_pdfs is no longer relevant as the function now hardcodes the path.
# However, to avoid breaking existing calls or requiring changes to the function signature,
# we'll keep the argument, but the function itself will override it.
all_pdf_documents=process_all_pdfs("dummy_path")

all_pdf_documents

## Text Splitting get into chunks

def split_text(documents,chunk_size=1000,chunk_overlap=200):
  """Split documents into smaller chunks for better RAG performance"""
  text_splitter=RecursiveCharacterTextSplitter(
      chunk_size=chunk_size,
      chunk_overlap=chunk_overlap,
      length_function=len,
      separators=["\n\n","\n"," ",""]
  )
  split_docs=text_splitter.split_documents(documents)
  print(f"Split {len(documents)} documents into {len(split_docs)} chunks")

  ## Show example of chunk
  if split_docs:
    print(f"\nExample chunk:")
    print(f"Content: {split_docs[0].page_content[:200]}...")
    print(f"Metadata: {split_docs[0].metadata}")

  return split_docs

chunks=split_text(all_pdf_documents)
chunks

"""**Embedding and VectorStore DB**"""

!pip install chromadb
import numpy as np
from sentence_transformers import SentenceTransformer
import chromadb
from chromadb.config import Settings
import uuid
from typing import List,Dict,Any,Tuple
from sklearn.metrics.pairwise import cosine_similarity

import numpy as np
from typing import List
from sentence_transformers import SentenceTransformer

class EmbeddingManager:
    """Handles document embedding generation using SentenceTransformer"""

    def __init__(self, model_name: str = "all-MiniLM-L6-v2"):
        """
        Initialize the EmbeddingManager with a SentenceTransformer model.
        """
        self.model_name = model_name      # FIXED
        self.model = None                 # FIXED
        self._load_model()

    def _load_model(self):
        """Load the SentenceTransformer Model"""
        try:
            print(f"Loading Embedding Model: {self.model_name}")
            self.model = SentenceTransformer(self.model_name)
            print(f"Embedding Model Loaded! Embedding dimension: {self.model.get_sentence_embedding_dimension()}")
        except Exception as e:
            print(f"Error loading embedding model {self.model_name}: {e}")
            raise

    def generate_embeddings(self, texts: List[str]) -> np.ndarray:
        """
        Generate embeddings for a list of texts.
        """
        if self.model is None:
            raise ValueError("Model not loaded")

        print(f"Generating embeddings for {len(texts)} texts...")
        embeddings = self.model.encode(texts, show_progress_bar=True)
        print(f"Generated embeddings with shape: {embeddings.shape}")
        return embeddings

    def get_sentence_embedding_dimension(self) -> int:
        """Get the dimension of sentence embeddings"""
        if self.model is None:
            raise ValueError("Model not loaded")
        return self.model.get_sentence_embedding_dimension()


# Initialize the embedding manager
embedding_manager = EmbeddingManager()
embedding_manager

"""**VectorStore**"""

class VectorStore:
    """Manages document embeddings inside a ChromaDB persistent vector store."""

    def __init__(self,
                 collection_name: str = "pdf_documents",
                 persist_directory: str = "./vector_store"):

        self.collection_name = collection_name
        self.persist_directory = persist_directory
        self.client = None
        self.collection = None

        self._initialize_vector_store()

    def _initialize_vector_store(self):
        """Initialize Chroma client and load/create collection."""
        try:
            os.makedirs(self.persist_directory, exist_ok=True)

            self.client = chromadb.PersistentClient(
                path=self.persist_directory
            )

            self.collection = self.client.get_or_create_collection(
                name=self.collection_name,
                metadata={"description": "PDF document embeddings for RAG"}
            )

            print(f"Vector Store Initialized → Collection: {self.collection_name}")
            print(f"Existing documents: {self.collection.count()}")

        except Exception as e:
            raise RuntimeError(f"Error initializing vector store: {e}")

    def add_documents(self, documents: List[Document], embeddings: np.ndarray):
        """Add documents + embeddings to the store."""

        if len(documents) != len(embeddings):
            raise ValueError("Documents count must match embeddings count")

        ids, metadatas, texts, embeddings_list = [], [], [], []

        print(f"Adding {len(documents)} documents to vector store...")

        for i, (doc, emb) in enumerate(zip(documents, embeddings)):
            doc_id = f"doc_{uuid.uuid4().hex[:8]}_{i}"
            ids.append(doc_id)

            metadata = dict(doc.metadata)
            metadata["chunk_id"] = i
            metadata["text_length"] = len(doc.page_content)
            metadatas.append(metadata)

            texts.append(doc.page_content)
            embeddings_list.append(emb.tolist())

        try:
            self.collection.add(
                ids=ids,
                documents=texts,
                metadatas=metadatas,
                embeddings=embeddings_list
            )

            print(f"Successfully added {len(ids)} documents.")
            print(f"Total stored: {self.collection.count()}")

        except Exception as e:
            raise RuntimeError(f"Error adding documents: {e}")

vectorstore = VectorStore()
vectorstore

chunks

texts = [chunk.page_content for chunk in chunks]
texts

# texts = list of strings from your chunks
texts = [chunk.page_content for chunk in chunks]

embeddings = embedding_manager.generate_embeddings(texts)
vectorstore.add_documents(chunks, embeddings)

"""**Retriever Pipeline From VectorStore**"""

import uuid
from typing import List, Dict, Any

class RAGRetriever:
    """Handles query-based retrieval from the vector store"""

    def __init__(self, vector_store, embedding_manager):
        self.vector_store = vector_store
        self.embedding_manager = embedding_manager

    def retrieve(self, query: str, top_k: int = 5, score_threshold: float = 0.0) -> List[Dict[str, Any]]:
        """
        Retrieve documents based on a query.
        """
        print(f"Retrieving documents for query: {query}")
        print(f"Top K: {top_k}, Score Threshold: {score_threshold}")

        # Generate query embedding
        query_embedding = self.embedding_manager.generate_embeddings([query])[0]

        # Search in vector space
        try:
            results = self.vector_store.collection.query(
                query_embeddings=[query_embedding.tolist()],
                n_results=top_k
            )

            # Process results
            retrieved_docs = []

            if results['documents'] and results['documents'][0]:
                documents = results['documents'][0]
                metadatas = results['metadatas'][0]
                scores = results['distances'][0]
                ids = results['ids'][0]

                # FIX: 'scores' was defined above, 'distances' was undefined in your loop
                for i, (doc_id, document, metadata, distance) in enumerate(zip(ids, documents, metadatas, scores)):

                    # Convert distance to similarity score
                    similarity_score = 1 - distance

                    if similarity_score >= score_threshold:
                        # FIX: changed retrieved_doc -> retrieved_docs
                        retrieved_docs.append({
                            'id': doc_id,
                            'content': document,
                            'metadata': metadata,
                            'similarity_score': similarity_score,
                            'distance': distance,
                            'rank': i + 1
                        })

                print(f"Retrieved {len(retrieved_docs)} documents (after filtering)")
            else:
                print("No documents found")

            return retrieved_docs

        except Exception as e:
            # The 'except' block is now aligned with 'try'
            raise RuntimeError(f"Error retrieving documents: {e}")


rag_retriever = RAGRetriever(vectorstore, embedding_manager)
rag_retriever

rag_retriever.retrieve("What is attention is all you need")

import os
import uuid
import chromadb
import numpy as np
from typing import List, Dict, Any

# ==========================================
# 1. Vector Store Class (Storage)
# ==========================================
class VectorStore:
    """Manages document embeddings inside a ChromaDB persistent vector store."""

    def __init__(self,
                 collection_name: str = "pdf_documents",
                 persist_directory: str = "./vector_store"):

        self.collection_name = collection_name
        self.persist_directory = persist_directory
        self.client = None
        self.collection = None

        self._initialize_vector_store()

    def _initialize_vector_store(self):
        """Initialize Chroma client and load/create collection."""
        try:
            os.makedirs(self.persist_directory, exist_ok=True)

            self.client = chromadb.PersistentClient(
                path=self.persist_directory
            )

            # CRITICAL FIX: We explicitly set the distance metric to "cosine".
            # This ensures that 'distance' returns a value between 0 and 1 (usually),
            # allowing us to use "Similarity = 1 - Distance".
            self.collection = self.client.get_or_create_collection(
                name=self.collection_name,
                metadata={"hnsw:space": "cosine"}
            )

            print(f"Vector Store Initialized → Collection: {self.collection_name}")
            print(f"Existing documents: {self.collection.count()}")

        except Exception as e:
            raise RuntimeError(f"Error initializing vector store: {e}")

    def reset_collection(self):
        """
        Deletes and recreates the collection.
        Run this if you changed embedding models or distance metrics.
        """
        try:
            self.client.delete_collection(self.collection_name)
            self._initialize_vector_store()
            print("Collection has been reset. Old data removed.")
        except Exception as e:
            print(f"Error resetting collection: {e}")

    def add_documents(self, documents: List[Any], embeddings: np.ndarray):
        """Add documents + embeddings to the store."""

        if len(documents) != len(embeddings):
            raise ValueError("Documents count must match embeddings count")

        ids, metadatas, texts, embeddings_list = [], [], [], []

        print(f"Adding {len(documents)} documents to vector store...")

        for i, (doc, emb) in enumerate(zip(documents, embeddings)):
            # Generate a unique ID for each chunk
            doc_id = f"doc_{uuid.uuid4().hex[:8]}_{i}"
            ids.append(doc_id)

            # safely get metadata and content
            metadata = dict(doc.metadata) if hasattr(doc, 'metadata') else {}
            metadata["chunk_id"] = i

            text_content = doc.page_content if hasattr(doc, 'page_content') else str(doc)
            metadata["text_length"] = len(text_content)

            metadatas.append(metadata)
            texts.append(text_content)
            embeddings_list.append(emb.tolist())

        try:
            self.collection.add(
                ids=ids,
                documents=texts,
                metadatas=metadatas,
                embeddings=embeddings_list
            )

            print(f"Successfully added {len(ids)} documents.")
            print(f"Total stored: {self.collection.count()}")

        except Exception as e:
            raise RuntimeError(f"Error adding documents: {e}")


# ==========================================
# 2. RAG Retriever Class (Search Logic)
# ==========================================
class RAGRetriever:
    """Handles query-based retrieval from the vector store"""

    def __init__(self, vector_store: VectorStore, embedding_manager):
        """
        Args:
        - vector_store: The initialized VectorStore instance
        - embedding_manager: Your existing embedding manager instance
        """
        self.vector_store = vector_store
        self.embedding_manager = embedding_manager

    def retrieve(self, query: str, top_k: int = 5, score_threshold: float = 0.0) -> List[Dict[str, Any]]:
        """
        Retrieve documents based on a query.
        """
        print(f"Retrieving documents for query: {query}")
        print(f"Top K: {top_k}, Score Threshold: {score_threshold}")

        # 1. Generate query embedding
        # We assume embedding_manager.generate_embeddings returns a list of arrays
        query_embedding = self.embedding_manager.generate_embeddings([query])[0]

        # 2. Search in vector space
        try:
            results = self.vector_store.collection.query(
                query_embeddings=[query_embedding.tolist()],
                n_results=top_k
            )

            retrieved_docs = []

            # 3. Process results if any exist
            if results['documents'] and results['documents'][0]:
                documents = results['documents'][0]
                metadatas = results['metadatas'][0]
                scores = results['distances'][0]  # These are Cosine Distances now
                ids = results['ids'][0]

                for i, (doc_id, document, metadata, distance) in enumerate(zip(ids, documents, metadatas, scores)):

                    # Convert Cosine Distance to Similarity Score
                    # Distance 0.1 -> Similarity 0.9
                    similarity_score = 1 - distance

                    if similarity_score >= score_threshold:
                        retrieved_docs.append({
                            'id': doc_id,
                            'content': document,
                            'metadata': metadata,
                            'similarity_score': similarity_score,
                            'distance': distance,
                            'rank': i + 1
                        })

                print(f"Retrieved {len(retrieved_docs)} documents (after filtering)")
            else:
                print("No documents found")

            return retrieved_docs

        except Exception as e:
            raise RuntimeError(f"Error retrieving documents: {e}")

# 1. Initialize
vectorstore = VectorStore()

# 2. RESET (Important: Run this once to switch to Cosine metric)
vectorstore.reset_collection()

# 3. Add your data again
# (Assuming 'chunks' and 'embedding_manager' are already defined in your notebook)
texts = [chunk.page_content for chunk in chunks]
embeddings = embedding_manager.generate_embeddings(texts)
vectorstore.add_documents(chunks, embeddings)

# 4. Search
retriever = RAGRetriever(vectorstore, embedding_manager)
results = retriever.retrieve("What is attention is all you need", score_threshold=0.1)

# 5. Show results
for res in results:
    print(f"\n[Score: {res['similarity_score']:.4f}] {res['content'][:150]}...")

results = retriever.retrieve("What is Transformer", score_threshold=0.1)

# 5. Show results
for res in results:
    print(f"\n[Score: {res['similarity_score']:.4f}] {res['content'][:150]}...")

results = retriever.retrieve("What is AlexNet", score_threshold=0.1)

# 5. Show results
for res in results:
    print(f"\n[Score: {res['similarity_score']:.4f}] {res['content'][:150]}...")

results = retriever.retrieve("Mathematical Formulation of AlexNet", score_threshold=0.1)

# 5. Show results
for res in results:
    print(f"\n[Score: {res['similarity_score']:.4f}] {res['content'][:150]}...")

results = retriever.retrieve("What is RAG", score_threshold=0.1)

# 5. Show results
for res in results:
    print(f"\n[Score: {res['similarity_score']:.4f}] {res['content'][:150]}...")

results = retriever.retrieve("unified-muti-task learning framework", score_threshold=0.1)

# 5. Show results
for res in results:
    print(f"\n[Score: {res['similarity_score']:.4f}] {res['content'][:150]}...")

"""**Integration VectorDB Context Pipeline with LLM output**"""

### Simple RAG pipeline with Groq LLM
from langchain_groq import ChatGroq
import os
from dotenv import load_dotenv
load_dotenv()

groq_api_key = "api-key"
# FIX: Changed model_name to a currently supported one, e.g., 'llama3-8b-8192'
llm=ChatGroq(groq_api_key=groq_api_key,model_name="llama-3.1-8b-instant",temperature=0.1,max_tokens=1024)

## Simple RAG Function : retrieve context + generate response

def rag_simple(query,retriever,llm,top_k=3):
    ## retrieve the context
    results = retriever.retrieve(query, top_k=top_k)
    context = "\n\n".join([doc["content"] for doc in results]) if results else "No relevant documents found"
    if not context:
      return "No relevant context found to answer the question"

    ## generate response using GROQ LLM

    prompt=f"""Use the Following context to answer the questin concisely.
          Context:
          {context}

          Question: {query}

          Answer:"""

    response=llm.invoke([prompt.format(context=context,query=query)])
    return response.content

answer=rag_simple("What is attention is all you need",retriever,llm)
answer

from langchain_groq import ChatGroq
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Setup LLM
# Note: Ideally, fetch this from os.getenv("GROQ_API_KEY") for security
groq_api_key = "api-key"

llm = ChatGroq(
    groq_api_key=groq_api_key,
    model_name="llama-3.1-8b-instant",
    temperature=0.1,
    max_tokens=1024
)

def rag_simple(query, retriever, llm, top_k=3):
    """
    Retrieves context, generates a response, and returns both the answer and sources.
    """
    ## 1. Retrieve the context
    results = retriever.retrieve(query, top_k=top_k)

    # Extract content
    context = "\n\n".join([doc["content"] for doc in results]) if results else ""

    if not context:
        return {
            "answer": "No relevant context found to answer the question",
            "sources": []
        }

    ## 2. Generate response using GROQ LLM
    # Fixed: Removed the redundant .format() call. The f-string handles the insertion.
    prompt = f"""Use the Following context to answer the question concisely.

    Context:
    {context}

    Question: {query}

    Answer:"""

    response = llm.invoke(prompt)

    ## 3. Return a dictionary with Answer AND Sources
    return {
        "answer": response.content,
        "sources": results
    }

# 1. Run the RAG function
output = rag_simple("What is attention is all you need", retriever, llm)

# 2. Print the Answer
print("=== Generated Answer ===")
print(output["answer"])
print("\n")

# 3. Print the Sources used
print("=== Source Documents ===")
for i, doc in enumerate(output["sources"]):
    # Adjust 'content' key if your retriever uses different keys (e.g. 'page_content')
    snippet = doc['content'].replace('\n', ' ')[:100]
    print(f"Source {i+1}: {snippet}...")

"""**Enhanced RAG Pipeline Features**"""

from sys import set_coroutine_origin_tracking_depth
def rag_advanced(query, retriever, llm, top_k=5, min_score=0.2,return_context=False):

    """
    RAG pipeline with extra features:
    - returns answer, sources, confidence score, and optionally fully context.
    """
    results=retriever.retrieve(query,top_k=top_k,score_threshold=min_score)
    if not results:
      return {'answer' : 'No relevant context found.','sources':[],'confidence':0.0,'context':''}

    # Prepare context and sources
    context="\n\n".join([doc['content'] for doc in results])
    sources=[{
        'source':doc['metadata'].get('source_file',doc['metadata'].get('source','unknown')),
        'page':doc['metadata'].get('page','unknown'),
        'score':doc['similarity_score'],
        'preview':doc['content'][:120] + '....'
    } for doc in results]
    confidence=max(doc['similarity_score'] for doc in results)

    ## Generate answer
    prompt=f"""Use the Following context to answer the question concisely.\nContext:\n{context}\n\nQuestion:{query}\n\nAnswer:"""
    response=llm.invoke([prompt.format(context=context,query=query)])

    output={
        'answer':response.content,
        'sources':sources,
        'confidence':confidence
    }
    if return_context:
        output['context']=context
    return output

## Example usage:
result=rag_advanced("What is attention mechanism?",retriever,llm,top_k=3,min_score=0.1,return_context=True)
print("Answer: ", result['answer'])
print("Source: ",result['sources'])
print("Confidence: ",result['confidence'])
print("Context: ",result['context'][:600])

result=rag_advanced("What is AlexNet?",retriever,llm,top_k=3,min_score=0.1,return_context=True)
print("Answer: ", result['answer'])
print("Source: ",result['sources'])
print("Confidence: ",result['confidence'])
print("Context: ",result['context'][:600])

result=rag_advanced("What is RAG?",retriever,llm,top_k=3,min_score=0.1,return_context=True)
print("Answer: ", result['answer'])
print("Source: ",result['sources'])
print("Confidence: ",result['confidence'])
print("Context: ",result['context'][:600])

from langchain_groq import ChatGroq
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Setup LLM
groq_api_key = "api-key"
llm = ChatGroq(
    groq_api_key=groq_api_key,
    model_name="llama-3.1-8b-instant",
    temperature=0.1,
    max_tokens=1024
)

def rag_advanced(query, retriever, llm, top_k=5, min_score=0.2, return_context=False):
    """
    Advanced RAG pipeline:
    - Retrieves documents with score filtering.
    - Generates a detailed response using the LLM.
    - Returns answer, structured sources, confidence score, and optional context.
    """

    # 1. Retrieve documents with scores
    # Note: Ensure your retriever actually supports 'score_threshold' and returns scores.
    results = retriever.retrieve(query, top_k=top_k, score_threshold=min_score)

    # Handle empty results
    if not results:
        return {
            'answer': 'No relevant context found to answer the question.',
            'sources': [],
            'confidence': 0.0,
            'context': ''
        }

    # 2. Prepare context and source metadata
    # We join content with separators to help the LLM distinguish documents
    context_text = "\n\n--- Document Separator ---\n\n".join(
        [doc['content'] for doc in results]
    )

    sources = []
    scores = []

    for doc in results:
        # Safely extract metadata with defaults
        meta = doc.get('metadata', {})
        score = doc.get('similarity_score', 0.0)
        scores.append(score)

        sources.append({
            'source': meta.get('source_file', meta.get('source', 'Unknown Source')),
            'page': meta.get('page', 'N/A'),
            'score': round(score, 4),
            'preview': doc['content'][:150].replace('\n', ' ') + '...'
        })

    # Calculate overall confidence (max score of retrieved docs)
    confidence = max(scores) if scores else 0.0

    # 3. Generate detailed Answer
    # We use a detailed system prompt to get a comprehensive answer
    prompt = f"""You are an expert assistant. Use the provided Context Documents to answer the Question in detail.

    Guidelines:
    1. Answer the question comprehensively using ONLY the provided context.
    2. If the answer involves multiple steps or concepts, break it down clearly.
    3. If the context does not contain the answer, explicitly state: "I cannot answer this based on the provided context."

    Context Documents:
    {context_text}

    Question: {query}

    Detailed Answer:"""

    # Direct invocation (f-string handles the variable insertion)
    response = llm.invoke(prompt)

    output = {
        'answer': response.content,
        'sources': sources,
        'confidence': confidence
    }

    if return_context:
        output['context'] = context_text

    return output

# --- Example Usage ---

# Run the function
result = rag_advanced(
    "What is attention mechanism?",
    retriever,
    llm,
    top_k=3,
    min_score=0.1,
    return_context=True
)

# --- Pretty Print Output ---
print(f"=== Q: What is attention mechanism? ===\n")

print("ANSWER:")
print(result['answer'])
print("\n" + "="*40 + "\n")

print(f"CONFIDENCE: {result['confidence']}\n")

print("SOURCES USED:")
for i, src in enumerate(result['sources']):
    print(f"  {i+1}. {src['source']} (Page {src['page']}) - Score: {src['score']}")
    print(f"     Preview: {src['preview']}\n")

if result['context']:
    print("RAW CONTEXT SNIPPET:")
    print(result['context'][:300] + "...\n")

from langchain_groq import ChatGroq
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Setup LLM
groq_api_key = "api-key"
llm = ChatGroq(
    groq_api_key=groq_api_key,
    model_name="llama-3.1-8b-instant",
    temperature=0.1,
    max_tokens=1024
)

def rag_advanced(query, retriever, llm, top_k=5, min_score=0.2, return_context=False):
    """
    Advanced RAG pipeline:
    - Retrieves documents with score filtering.
    - Generates a detailed response using the LLM.
    - Returns answer, structured sources, confidence score, and optional context.
    """

    # 1. Retrieve documents with scores
    # Note: Ensure your retriever actually supports 'score_threshold' and returns scores.
    results = retriever.retrieve(query, top_k=top_k, score_threshold=min_score)

    # Handle empty results
    if not results:
        return {
            'answer': 'No relevant context found to answer the question.',
            'sources': [],
            'confidence': 0.0,
            'context': ''
        }

    # 2. Prepare context and source metadata
    # We join content with separators to help the LLM distinguish documents
    context_text = "\n\n--- Document Separator ---\n\n".join(
        [doc['content'] for doc in results]
    )

    sources = []
    scores = []

    for doc in results:
        # Safely extract metadata with defaults
        meta = doc.get('metadata', {})
        score = doc.get('similarity_score', 0.0)
        scores.append(score)

        sources.append({
            'source': meta.get('source_file', meta.get('source', 'Unknown Source')),
            'page': meta.get('page', 'N/A'),
            'score': round(score, 4),
            'preview': doc['content'][:150].replace('\n', ' ') + '...'
        })

    # Calculate overall confidence (max score of retrieved docs)
    confidence = max(scores) if scores else 0.0

    # 3. Generate detailed Answer
    # We use a detailed system prompt to get a comprehensive answer
    prompt = f"""You are an expert assistant. Use the provided Context Documents to answer the Question in detail.

    Guidelines:
    1. Answer the question comprehensively using ONLY the provided context.
    2. If the answer involves multiple steps or concepts, break it down clearly.
    3. If the context does not contain the answer, explicitly state: "I cannot answer this based on the provided context."

    Context Documents:
    {context_text}

    Question: {query}

    Detailed Answer:"""

    # Direct invocation (f-string handles the variable insertion)
    response = llm.invoke(prompt)

    output = {
        'answer': response.content,
        'sources': sources,
        'confidence': confidence
    }

    if return_context:
        output['context'] = context_text

    return output

# --- Example Usage ---

# Run the function
result = rag_advanced(
    "What is AlexNet?",
    retriever,
    llm,
    top_k=3,
    min_score=0.1,
    return_context=True
)

# --- Pretty Print Output ---
print(f"=== Q: What is attention mechanism? ===\n")

print("ANSWER:")
print(result['answer'])
print("\n" + "="*40 + "\n")

print(f"CONFIDENCE: {result['confidence']}\n")

print("SOURCES USED:")
for i, src in enumerate(result['sources']):
    print(f"  {i+1}. {src['source']} (Page {src['page']}) - Score: {src['score']}")
    print(f"     Preview: {src['preview']}\n")

if result['context']:
    print("RAW CONTEXT SNIPPET:")
    print(result['context'][:600] + "...\n")

from langchain_groq import ChatGroq
import os
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Setup LLM
groq_api_key = "api-key"
llm = ChatGroq(
    groq_api_key=groq_api_key,
    model_name="llama-3.1-8b-instant",
    temperature=0.1,
    max_tokens=1024
)

def rag_advanced(query, retriever, llm, top_k=5, min_score=0.2, return_context=False):
    """
    Advanced RAG pipeline:
    - Retrieves documents with score filtering.
    - Generates a detailed response using the LLM.
    - Returns answer, structured sources, confidence score, and optional context.
    """

    # 1. Retrieve documents with scores
    # Note: Ensure your retriever actually supports 'score_threshold' and returns scores.
    results = retriever.retrieve(query, top_k=top_k, score_threshold=min_score)

    # Handle empty results
    if not results:
        return {
            'answer': 'No relevant context found to answer the question.',
            'sources': [],
            'confidence': 0.0,
            'context': ''
        }

    # 2. Prepare context and source metadata
    # We join content with separators to help the LLM distinguish documents
    context_text = "\n\n--- Document Separator ---\n\n".join(
        [doc['content'] for doc in results]
    )

    sources = []
    scores = []

    for doc in results:
        # Safely extract metadata with defaults
        meta = doc.get('metadata', {})
        score = doc.get('similarity_score', 0.0)
        scores.append(score)

        sources.append({
            'source': meta.get('source_file', meta.get('source', 'Unknown Source')),
            'page': meta.get('page', 'N/A'),
            'score': round(score, 4),
            'preview': doc['content'][:150].replace('\n', ' ') + '...'
        })

    # Calculate overall confidence (max score of retrieved docs)
    confidence = max(scores) if scores else 0.0

    # 3. Generate detailed Answer
    # We use a detailed system prompt to get a comprehensive answer
    prompt = f"""You are an expert assistant. Use the provided Context Documents to answer the Question in detail.

    Guidelines:
    1. Answer the question comprehensively using ONLY the provided context.
    2. If the answer involves multiple steps or concepts, break it down clearly.
    3. If the context does not contain the answer, explicitly state: "I cannot answer this based on the provided context."

    Context Documents:
    {context_text}

    Question: {query}

    Detailed Answer:"""

    # Direct invocation (f-string handles the variable insertion)
    response = llm.invoke(prompt)

    output = {
        'answer': response.content,
        'sources': sources,
        'confidence': confidence
    }

    if return_context:
        output['context'] = context_text

    return output

# --- Example Usage ---

# Run the function
result = rag_advanced(
    "What is RAG",
    retriever,
    llm,
    top_k=3,
    min_score=0.1,
    return_context=True
)

# --- Pretty Print Output ---
print(f"=== Q: What is RAG? ===\n")

print("ANSWER:")
print(result['answer'])
print("\n" + "="*40 + "\n")

print(f"CONFIDENCE: {result['confidence']}\n")

print("SOURCES USED:")
for i, src in enumerate(result['sources']):
    print(f"  {i+1}. {src['source']} (Page {src['page']}) - Score: {src['score']}")
    print(f"     Preview: {src['preview']}\n")

if result['context']:
    print("RAW CONTEXT SNIPPET:")
    print(result['context'][:300] + "...\n")

